### ISSUE TITLE
version error？

### ISSUE THREAD

**Issue by lz666win** [Simoncarbo/Ultras-Sound-Nerve-Segmentation---Kaggle#2]
I use theano0.9.0 and keras 1.0.7,here is the error:
Traceback (most recent call last):
  File "C:/Users/lz666/PycharmProjects/Ultras-Sound-Nerve-Seg-Kaggle/train.py", line 115, in <module>
    model,epoch_history = train_segment(train_imgs,train_masks,train_index,train_i,val_i,factor,factor_val)
  File "C:/Users/lz666/PycharmProjects/Ultras-Sound-Nerve-Seg-Kaggle/train.py", line 86, in train_segment
    validation_data = (train_imgs[val_i], train_masks[val_i]))
  File "C:\Users\lz666\AppData\Local\conda\conda\envs\maskrcnn\lib\site-packages\keras\engine\training.py", line 1387, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
when I use keras1.5.0,there is an other error:no model called layers.LocallyConnected2D,so what version did you use?

**Comment by Simoncarbo** [comment]
You can find this information in the readme:
"The code runs on Python 3.4 and the Keras (1.0.5) library with Theano (0.9.0) backend. "

**Comment by lz666win** [comment]
I know,even I use python 3.6,but I use the same version of keras and theano,I think it is Nothing to do with python version.
by the way,I change model.fit_generator by model.fit,it did not train for longtime.

**Comment by Simoncarbo** [comment]
Code for the data generator is in Utils/data_management.py, I think you'll have to look into it to solve you're bug...

I'm sorry I can't help you more.
